### ISSUE TITLE
Helm chart fails if tls is enabled

### ISSUE THREAD

**Issue by lgeiger** [polyaxon/polyaxon-chart#37]
I tried to follow the SSL guide [here](https://docs.polyaxon.com/configuration/ssl/#nginx-for-polyaxon-running-with-a-nodeport-service) with the example ingress configuration:
```yaml
serviceType: ClusterIP
ingress:
  enabled: true
  hostName: polyaxon.acme.com
  tls:
  - secretName: polyaxon.acme-tls
    hosts:
      - polyaxon.acme.com
```

Unfortunately `helm upgrade` using version 0.4.3 fails with the following error:
```
Error: YAML parse error on polyaxon/templates/ing.yaml: error converting YAML to JSON: yaml: line 39: did not find expected '-' indicator
Error: UPGRADE FAILED: YAML parse error on polyaxon/templates/ing.yaml: error converting YAML to JSON: yaml: line 39: did not find expected '-' indicator
```

I seams like [this line](https://github.com/polyaxon/polyaxon-chart/blob/master/polyaxon/templates/ing.yaml#L39) is causing the trouble.
For now switching back to http works for me, or am I missing something?
