### ISSUE TITLE
Following the instructions on ReadME for experiment and job fails in yaml.

### ISSUE THREAD

**Issue by hollowgalaxy** [polyaxon/polyaxon-chart#54]
With the yaml 
```
---
version: 1
kind: job
environment:
  persistence:
    data:
        mountPath: "/data"
        existingClaim: "pvc-data"
        readOnly: false
  resources:
    cpu:
      limits: 1
      requests: 1
    memory:
      requests: 5120
      limits: 5120

build:
  dockerfile: polyaxon/Dockerfile
run:
  cmd:
    - python polyaxon/temp.py
    - sleep 10
```
I get the error: ```Polyaxonfile is not valid.
Error message `{'environment': {'persistence': {'data': ['Not a valid list.']}}}`.```
